### ISSUE TITLE
USN-MSc.cls No linebreak. Simple project option

### ISSUE THREAD

**Issue by JorundMartinsen** [dietmarw/USN-LaTeX#2]
There is no linebreak in the project option of the title page, however there is linebreaks in the thesis option.
Line 83 <= Line 101

Also, consider adding a 'simple project' option. This will ease use for simple projects that does not need the summary page.

- J. Martinsen

**Comment by dietmarw** [comment]
Thanks for the feedback. I will look at those issues next week.

**Comment by dietmarw** [comment]
OK fixed the linebreak issue and added a new "nosummary" option.
