### ISSUE TITLE
Issue with front-page figure.

### ISSUE THREAD

**Issue by larsRikard** [dietmarw/USN-LaTeX#4]
Hello! 👋

I'm new to LaTeX, but i manage to do most of the same things I do in MS Word now by using this template.
Anyways, I'm trying to add a figure to the title page (front page), but it doesn't look like it is working. It looks like the BScThesis.pdf and MScThesis.pdf examples provided in this repo have the same problem. Is this intentional? Am I supposed to use \begin{figure} for the title page?

![image](https://user-images.githubusercontent.com/9643252/191272881-b438f583-0b50-4b66-a901-e1b9c1d2ae57.png)

**Comment by dietmarw** [comment]
Hi, it looks like you referenced the image with `fig//TomatoPickerBot.png`,i.e., with two `//` instead of just one. Could you try to use:
`fig/TomatoPickerBot`  (the .png extension is actually not needed).

**Comment by larsRikard** [comment]
Well, perhaps it turns out like that internally. This is the code in MScThesis.tex that produce this result:

```
% --- title page setup ---
\USNtitlepage%
%% Please provide the following information:
%% #1 optional figure (set to {} if not wanted)
{%
  {\normalsize <optional figure>}
   \includegraphics[draft,width=\textwidth]{TomatoPickerBot}}
```

Am I supposed to edit other files?

**Comment by dietmarw** [comment]
Ah, now I see the problem. Simply remove `draft` and it should work.
`\includegraphics[width=\textwidth]{TomatoPickerBot}`
